### ISSUE TITLE
AttributeError: module 'audioowl' has no attribute 'analyze_file'

### ISSUE THREAD

**Issue by RustyDev** [dodiku/AudioOwl#3]
Hi, I'm trying to test out a simple file and am getting the error:

    AttributeError: module 'audioowl' has no attribute 'analyze_file'

I'm running Python 3.66

    import audioowl
    data = audioowl.analyze_file(path='squishy.wav', sr=22050)
    print (data)

Any idea what could be going on?

**Comment by dodiku** [comment]
Hi,

I'm running the same operation with Python 3.6.5 (should be no different) and I can't reproduce the issue. Everything is working fine :)

Can you please recheck your environment?

Please feel free to reopen if you still face this problem.
